### ISSUE TITLE
Just a minor question.

### ISSUE THREAD

**Issue by ghost** [nt-games-ytb/Minecraft-Wii-U-IP-Sniffer#1]
English: What's the point of putting a password on the compiled release if you also freely release the source code with no restrictions? Someone can just download the source and build it just as easily as downloading the EXE File. So your caution is a bit misplaced. To add to the matter, you shouldn't worry too much about the community. Most people are too inexperienced to do literally anything with the information given by this tool, or any others for that matter. For example a few have been floating around including ones that me and WiiUCodes distribute. The worst that's happened is some random kid pulls an IP to scare another kid but it does not go much past that.

French (translated): Quel est l'intérêt de mettre un mot de passe sur la version compilée si vous publiez aussi librement le code source sans aucune restriction ? Quelqu'un peut télécharger le code source et le compiler aussi facilement que le fichier EXE. Votre prudence est donc un peu déplacée. Pour ajouter à la question, vous ne devriez pas trop vous inquiéter de la communauté. La plupart des gens sont trop inexpérimentés pour faire quoi que ce soit avec les informations fournies par cet outil, ou tout autre outil d'ailleurs. Par exemple, il y en a eu quelques-uns qui ont circulé, y compris ceux que WiiUCodes et moi distribuons. Le pire qui soit arrivé, c'est qu'un enfant au hasard tire une adresse IP pour effrayer un autre enfant, mais cela ne va pas beaucoup plus loin.

**Comment by ghost** [comment]
By the way, reconstructing the main form file really isn't that hard. Already did it and compiled the program. If you're worried about something doing damage and you're trying to put passwords on it, then just don't release it.

Also I already have the passwords to the RAR files. It's not hard to crack a hash on a ZIP / RAR.

If you really want to secure it in a way that won't be easily circumvented then I would suggest making a REALLY long password, and translating it to base64 multiple times. It'd take months to get through that.

**Comment by mpxt** [comment]
I hope that the password will not be found because often with a site we can find where you live (not necessarily the exact address but one or two cities nearby) if it's that easy to compile the software, crack the password or if the password leak i better stay away from Minecraft WiiU online 😅

**Comment by hataodev** [comment]
I hope that the password will not be found because often with a site we can find where you live (not necessarily the exact address but one or two cities nearby) if it's that easy to compile the software, crack the password or if the password leak i better stay away from Minecraft WiiU online 😅

**Comment by hataodev** [comment]
I admit it's a little scary to hear that

**Comment by ghost** [comment]
Don't be too scared. It may be easy for me, but then again I'm pretty well seasoned in reverse engineering and cracking even base ASM Elements. Hence how me and my team cracks Wii U Mod Clients like PureClient. (Although WiiUCodes did most of the work on the ASM lol)

Plus those websites people use to track IP Address information are SUPERRR inaccurate. They point the info of your ISP, since all the information from your IP is housed in their buildings, since it's using their servers. Most of the time the closest you'll get is the state. Even getting the right City is kinda rare.. To get an actual home-address requires some.. less than legal methods, lol.

**Comment by hataodev** [comment]
it becomes more reassuring ^^ lol
Btw are you still trying to crack Trinity?

**Comment by ghost** [comment]
> Btw are you still trying to crack Trinity?

Technically we already know how, but just haven't gotten around to doing so. The obfuscated contents can all be decrypted by simply getting the key from the .elf held on their server. Someone else already did this so we didn't feel a need to pursue it. On top of that Trinity is basically irrelevant at this point especially with things like Pure already being cracked.

Anyways we shouldn't clog the issues page. If you wanna talk to me then contact me via instagram or gmail. (Before you ask, no I dont have Discord)

Instagram: korozin_alt
gmail: mammothasdfman@gmail.com

**Comment by hataodev** [comment]
> > On top of that Trinity is basically irrelevant at this point especially with things like Pure already being cracked.

Oh okay 👍
There is a lot of client now but PureClient is for the moment the best for me lol

**Comment by cedkeChat** [comment]
ok

**Comment by nt-games-ytb** [comment]
Hi.

First I would like to remind you that the main code is password protected. It may be rebuildable but you need a little experience in C# (I know that you have it, but I'm speaking for other children who don't know much about it). In fact, if someone manages to get the password or manages to rebuild the software I will be happy for him and I will congratulate him.

Personally I wanted to put everything in public, without password, but I gave up after several requests from my friends.

I know that a password for a .RAR/.ZIP file is easily cracked, so I put a password with more than 100 characters. I could have done better but I liked the idea of my password (I wouldn't say it of course).

Thank you in any case for giving me your opinion and information.

**Comment by ghost** [comment]
The main reason I don't understand the efforts behind it is because of the fact that there are already a ton of different IP Sniffing methods available on the Wii U already. Most of the damage has already been done, so this couldn't do much more harm.

For example in one of the Mod Archives me and my friends host we have a code that's publicly available that literally just display's the Host's IP on your screen in-game. We also have a Python Script that lists all the IPs in the server. The only different thing this offers is just integrating the same process into a new GUI so there's really nothing new to worry about. But then again that being said this is your RTM and Repo, so you're free to do what you want with it. Just stating opinions here.

**Comment by nt-games-ytb** [comment]
As I told you I preferred not to put a password so it's not really my choice to make (I don't want to alienate anyone and I want people to agree, in fact I don't care if people use my software or not). I knew before that how to sniff people's IP with Cain Abel for example and other people know how to sniff an IP but I think all the people who asked me to put a password are afraid that little children who didn't know how to do it will now know how to do it.

The French are (excuse me for saying this) a little late, a little stupid and they seek the simplicity. As I am generally known in France (being French myself), the French will trust me and will be aware that I made this software, whereas if it is a Japanese (for example) who made this, the news will be less popularized and some will be afraid that it is a virus or other. Of course it works both ways. The people who told me not to make it public are 80% french and they are simply afraid for the French community where ip sniffing is rare.

**Comment by ghost** [comment]
True, and I see your point. But people should also know that getting your IP pulled isnt nearly as scary as people make it out to be. At most people will just try to scare you with the fact they have it, other than that it's kind of hard to do much else with it without being susceptible to law enforcement intervention. And even then, most people don't even know how to get that far.

**Comment by nt-games-ytb** [comment]
I wanted to inform you that after the release of Trinity V3 I decided to remove the password.
